version: '3'
services:
    web:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./inside/nginx:/usr/share/nginx/html

    db:
        image: mysql:latest
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: example
            MYSQL_DATABASE: db_test
            MYSQL_USER: trmd
            MYSQL_PASSWORD: trmd
        volumes:
            - ./mysql_data:/var/lib/mysql
        ports:
            - "3346:3346"

    phpmyadmin:
        image: phpmyadmin
        container_name: pma
        depends_on:
            - db
        environment:
              PMA_HOST: db
              MYSQL_ROOT_PASSWORD: example
        restart: always
        ports:
              - 8085:80
