version: '3'
services:
    web:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./inside/nginx:/usr/share/nginx/html

    db:
        image: mysql:latest
        restart: always
        environment:
        MYSQL_ROOT_PASSWORD: admin
        MYSQL_DATABASE: database
        MYSQL_USER: user
        MYSQL_PASSWORD: user
        volumes:
        - ./inside/mysql:/var/lib/mysql
        ports:
        - "3306:3306"
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        restart: always
        depends_on:
        - db
        environment:
        PMA_HOST: db
        MYSQL_ROOT_PASSWORD: admin
        ports:
        - "8090:80"
